# https://wiki.kavitareader.com/installation/docker/dockerhub/
services:
    kavita:
        image: jvmilazz0/kavita:latest
        container_name: kavita
        volumes:
            - /home/${USER}/books:/books
            - ./config:/kavita/config     # /kavita/config must not be changed
        environment:
            - TZ=Europe/Berlin
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        ports:
            - "5000:5000"
        restart: unless-stopped
